# Generated by Django 3.1.7 on 2021-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetId', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.CharField(max_length=280)),
            ],
        ),
    ]
