# Generated by Django 3.1.7 on 2021-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraptwitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.CharField(max_length=280)),
            ],
        ),
    ]
